---
- name: installing apache and php on ubuntu 20.04
  hosts: all
  become: yes
  vars: 
    apache_package: apache2
    php_package: php libapache2-mod-php php-mysql
    src_path: ./php.txt
    dest_path: /var/www/html/info.php
  tasks:
    - name: install apache
      ansible.builtin.apt:
        name: "{{ apache_package }}"
        state: present
    - name: install apache
      ansible.builtin.apt:
        name: 
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
    - name: inserting info.php
      ansible.builtin.copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"










