---
- name: installing apache and php
  hosts: all
  become: yes
  vars:
    src_path: ./php.txt
    dest_path: /var/www/html/info.php
  tasks:
    - name: package installation
      ansible.builtin.package:
        name: 
         - "{{ apache_package }}"
         - "{{ php_package }}"
        state: present

    - name: copying the php info file
      ansible.builtin.copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"

    - name: starting apache2 service in ubuntu
      ansible.builtin.service:
        name: apache2.service 
        state: started 
      when: ansible_facts['os_family'] == "Debian"

    - name: starting httpd service in centos
      ansible.builtin.service:       
        name: httpd.service
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "CentOs" 


