---
- name: installing tomcat 9/10/11
  hosts: all
  become: yes
  vars:
    tomcat_version: 10.1.5
    tomcat_user_name: tomcat
    tomcat_group_name: tomcat
    tomcat_home_directory: /opt/tomcat
    tomcat_shell: /bin/false
    tomcat_tar_file_url: 
  tasks:
    - name: Installing java    
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present  

    - name: Creating the tomcat group 
      ansible.builtin.group:
        name: "{{ tomcat_group_name }}"
        state: present 
        system: yes 

    - name:  Creating the user and add to group  
      ansible.builtin.user:
        name: "{{ tomcat_user_name }}"
        group: "{{ tomcat_group_name }}"
        home: "{{ tomcat_home_directory }}"
        shell: "{{ tomcat_shell }}"
        state: present
        system: yes     

    - name: Downloading the tomcat url    
      ansible.builtin.get_url:
        url: "https://www-eu.apache.org/dist/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /tmp/   

    - name: untar the tomcat tar file in /opt/tomcat/    
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_home_directory }}"
        remote_src: yes

    - name: creating symbolic link for control over versions   
      ansible.builtin.file:
        src: "{{ tomcat_home_directory }}t/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_home_directory }}/latest"
        owner: "{{ tomcat_user_name }}"
        group: "{{ tomcat_group_name }}"
        state: link

    - name: given ownership permission to user and group tomcat
      ansible.builtin.file:
        path: "{{ tomcat_home_directory }}"
        owner: "{{ tomcat_user_name }}"
        group: "{{ tomcat_group_name }}"
        mode: "+x"
        recurse: yes
        state: directory
  
    - name: give executable permissions to .sh files
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 'a+x'
      with_fileglob:
        - "{{ tomcat_home_directory }}/latest/bin/*.sh" 
 
    - name: copying tomcat service files
      ansible.builtin.copy:
        src: tomcat.service  
        dest: /etc/systemd/system/tomcat.service
      notify: 
        - daemon reload  

    - name: creating users
      ansible.builtin.copy:
        src: tomcat-users.xml  
        dest: "{{ tomcat_home_directory }}/latest/conf/tomcat-users.xml"

    - name: copy the context file 
      ansible.builtin.copy:
        src: context.xml  
        dest: "{{ item  }}"
        owner: "{{ tomcat_user_name }}"
        group: "{{ tomcat_group_name }}"
      loop:
        - "{{ tomcat_home_directory }}/webapps/manager/META-INF/context.xml"
        - "{{ tomcat_home_directory }}/latest/webapps/manager/META-INF/context.xml"
      notify:
        - daemon_reload

  handlers:
    - name: daemon reload 
      ansible.builtin.systemd:
        name: tomcat
        state: restarted    
        daemon_reload: yes
        enabled: yes





