---
- name: installing apache and php on ubuntu 22.04
  hosts: all
  become: yes
  vars: 
    apache_package: apache2
  tasks:
    - name: install apache
      ansible.builtin.apt:
        name: "{{ apache_package }}"
        state: present
